#!/bin/bash
# file name preinst
# Pre-install script for tera. This removes old versions o tera.

echo "Installing niah web ..."

sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
sudo cp /usr/share/niah-web/nginx.conf /etc/nginx/nginx.conf
sudo service nginx restart

sudo cp -r /usr/share/niah-web/src/* /var/www/html/
sudo chmod 755 /var/www/html/ -R

