#!/bin/bash
# file name preinst
# Pre-install script for tera. This removes old versions o tera.

echo "Installing niah web ..."

sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
sudo cp /usr/share/niah-web/nginx.conf /etc/nginx/nginx.conf
sudo cp /usr/share/niah-web/default /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

sudo cp -r /usr/share/niah-web/src/* /var/www/html/
sudo chmod 755 /var/www/html/ -R

FILE=/home/niah/niah-api

FILEG=/var/www/html/env-config.js.org

if [ ! -f "$FILEG" ]; then
    cp /var/www/html/env-config.js /var/www/html/env-config.js.org
fi

if [ -f "$FILE" ]; then
    API_IP=$(curl ifconfig.me)
    sed "s/127.0.0.1/$API_IP/g" /var/www/html/env-config.js.org > /var/www/html/env-config.js
fi

